---
- name: Install Apache Web Server
  hosts: webservers
  become: true
  ansible_user: mohan
  ansible_ssh_private_key_file: ~/.ssh/id_rsa
  ansible_become_password: QWERTY@2002

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes
